version: '3'

services:

  # Nats
  nats-server:
    image: nats:latest
   
  # Gateway 
  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: us-east1-docker.pkg.dev/ms-store-459001/ms-store-registry/client-gateway-production
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    environment:
      - PORT=3000
      - PRODUCTS_MICROSERVICE_HOST=localhost
      - PRODUCTS_MICROSERVICE_PORT=3001
      - ORDERS_MICROSERVICE_HOST=localhost
      - ORDERS_MICROSERVICE_PORT=3002
      - NATS_SERVERS=nats://nats-server:4222

  # Products MS
  products-ms:
    build: 
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: us-east1-docker.pkg.dev/ms-store-459001/ms-store-registry/products-ms
    environment:
      - PORT=3001
      - PRODUCTS_MICROSERVICE_HOST=localhost
      - PRODUCTS_MICROSERVICE_PORT=3001
      - ORDERS_MICROSERVICE_HOST=localhost
      - ORDERS_MICROSERVICE_PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  # Orders MS
  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_MS_DATABASE_URL}
    image: us-east1-docker.pkg.dev/ms-store-459001/ms-store-registry/orders-ms
    environment:
      - PORT=3002
      - PRODUCTS_MICROSERVICE_HOST=localhost
      - PRODUCTS_MICROSERVICE_PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_MS_DATABASE_URL}

  payments-ms:
    build: 
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: us-east1-docker.pkg.dev/ms-store-459001/ms-store-registry/payments-ms
    ports:
      - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_ENDPOINTSECRET=${STRIPE_ENDPOINTSECRET}


  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: us-east1-docker.pkg.dev/ms-store-459001/ms-store-registry/auth-ms
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_MS_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}