apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client-gateway
  name: client-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client-gateway
    spec:
      containers:
        - image: us-east1-docker.pkg.dev/ms-store-459001/ms-store-registry/client-gateway-production
          name: client-gateway-production
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: PRODUCTS_MICROSERVICE_HOST
              value: localhost
            - name: PRODUCTS_MICROSERVICE_PORT
              value: "3001"
            - name: ORDERS_MICROSERVICE_HOST
              value: localhost
            - name: ORDERS_MICROSERVICE_PORT
              value: "3002"
            - name: NATS_SERVERS
              value: "nats://nats"
          resources: {}
status: {}
