apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: products-ms
  name: products-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: products-ms
    spec:
      containers:
        - image: us-east1-docker.pkg.dev/ms-store-459001/ms-store-registry/products-ms
          name: products-ms
          env:
            - name: PORT
              value: "3001"
            - name: PRODUCTS_MICROSERVICE_HOST
              value: "localhost"
            - name: PRODUCTS_MICROSERVICE_PORT
              value: "3001"
            - name: ORDERS_MICROSERVICE_HOST
              value: "localhost"
            - name: ORDERS_MICROSERVICE_PORT
              value: "3002"
            - name: NATS_SERVERS
              value: "nats://nats"
            - name: DATABASE_URL
              value: "file:./dev.db"

          resources: {}
status: {}
